### ISSUE TITLE
Error in sess = tf.Session() segment

### ISSUE THREAD

**Issue by aperwe** [aperwe/GANs#1]
**Solve error:** 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-b5c739df9f80> in <module>()
     17 
     18 #(g(z))
---> 19 Gz = generator(batch_size, z_dimensions)
     20 #Gz holds the generated images
     21 

<ipython-input-3-15af6e30ecf9> in generator(batch_size, z_dim)
     14     #First deconv block
     15     #3136 = 28 * 28 * 4
---> 16     g_w1 = tf.get_variable('g_w1', [z_dim, 3136], dtype = tf.float32, initializer = tf.truncated_normal_initializer(stddev=0.02))
     17     g_b1 = tf.get_variable('g_b1', [3136], initializer = tf.truncated_normal_initializer(stddev = 0.02))
     18     g1 = tf.matmul(z, g_w1) + g_b1

E:\Artur\Development\Anaconda3\envs\MachineLearningPython3\lib\site-packages\tensorflow\python\ops\variable_scope.py in get_variable(name, shape, dtype, initializer, regularizer, trainable, collections, caching_device, partitioner, validate_shape, use_resource, custom_getter, constraint)
   1315       partitioner=partitioner, validate_shape=validate_shape,
   1316       use_resource=use_resource, custom_getter=custom_getter,
-> 1317       constraint=constraint)
   1318 get_variable_or_local_docstring = (
   1319     """%s

E:\Artur\Development\Anaconda3\envs\MachineLearningPython3\lib\site-packages\tensorflow\python\ops\variable_scope.py in get_variable(self, var_store, name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, use_resource, custom_getter, constraint)
   1077           partitioner=partitioner, validate_shape=validate_shape,
   1078           use_resource=use_resource, custom_getter=custom_getter,
-> 1079           constraint=constraint)
   1080 
   1081   def _get_partitioned_variable(self,

E:\Artur\Development\Anaconda3\envs\MachineLearningPython3\lib\site-packages\tensorflow\python\ops\variable_scope.py in get_variable(self, name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, use_resource, custom_getter, constraint)
    423           caching_device=caching_device, partitioner=partitioner,
    424           validate_shape=validate_shape, use_resource=use_resource,
--> 425           constraint=constraint)
    426 
    427   def _get_partitioned_variable(

E:\Artur\Development\Anaconda3\envs\MachineLearningPython3\lib\site-packages\tensorflow\python\ops\variable_scope.py in _true_getter(name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, use_resource, constraint)
    392           trainable=trainable, collections=collections,
    393           caching_device=caching_device, validate_shape=validate_shape,
--> 394           use_resource=use_resource, constraint=constraint)
    395 
    396     if custom_getter is not None:

E:\Artur\Development\Anaconda3\envs\MachineLearningPython3\lib\site-packages\tensorflow\python\ops\variable_scope.py in _get_single_variable(self, name, shape, dtype, initializer, regularizer, partition_info, reuse, trainable, collections, caching_device, validate_shape, use_resource, constraint)
    731                          "reuse=tf.AUTO_REUSE in VarScope? "
    732                          "Originally defined at:\n\n%s" % (
--> 733                              name, "".join(traceback.format_list(tb))))
    734       found_var = self._vars[name]
    735       if not shape.is_compatible_with(found_var.get_shape()):

**ValueError: Variable g_w1 already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope?** Originally defined at:

  File "E:\Artur\Development\Anaconda3\envs\MachineLearningPython3\lib\site-packages\tensorflow\python\framework\ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
  File "E:\Artur\Development\Anaconda3\envs\MachineLearningPython3\lib\site-packages\tensorflow\python\framework\ops.py", line 3392, in create_op
    op_def=op_def)
  File "E:\Artur\Development\Anaconda3\envs\MachineLearningPython3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)

**Comment by aperwe** [comment]
Fixed with
Jedna poprawka z reuse variables naprawiła jeden fragment kodu:
trzeba zmienić
with tf.variable_scope(tf.get_variable_scope()) as scope:
na
with tf.variable_scope(tf.get_variable_scope(), reuse = tf.AUTO_REUSE) as scope:
